name: Example Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 23f3001608@ds.study.iitm.ac.in
        run: echo "Hello, world!"
